#import "./fragments/customer-error.gql"

mutation customerReset($id: ID!, $input: CustomerResetInput!) {
	mutation: customerReset(id: $id, input: $input) {
		userErrors: customerUserErrors { ...customerUserError }
	}
}
